### ISSUE TITLE
Support for 2024.2.1

### ISSUE THREAD

**Issue by stecon02** [manu156/jpqltosql#11]
Are there any plans to add support for the latest version? (2024.2.1)

**Comment by manu156** [comment]
@stecon02 yes, I will try to release the update by 20th September. I will also fix bugs if there are any (please report if you have faced some issues), I didn't get time to properly test current version.

**Comment by manu156** [comment]
closing this as plugin is published for 2024.2.1 as version 1.3.1. I will release one more version by 20th September with bug fixes
